version: '3.7'
services:
  vue:
    image: node:lts-alpine
    volumes:
      - .:/opt/app
    user: "1000:1000"
    ports:
      - "9000:9000"
    working_dir: /opt/app
    command: ["sh", "-c", "yarn install && yarn serve"]
